name: My CI

on: push

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Testing..."
